### ISSUE TITLE
Add raw data to data-raw folder

### ISSUE THREAD

**Issue by larnsce** [Global-Health-Engineering/durbanplasticwaste#1]
@raulalexb, please add the data to this folder:

https://github.com/Global-Health-Engineering/datadurbanplasticwaste22/tree/main/data-raw

and then commit to finalise.

**Comment by raulalexb** [comment]
Hi @larnsce ! I am currently preparing my data for the transfer to a .csv file and I stumbled upon following question:
Can I leave empty cells empty (without any data), in hopes that they will store the number "0" when transfered as a .csv file? Or do I explicitly have to write 0 in those cells? Thanks ;)

**Comment by larnsce** [comment]
Hi @raulalexb. Thanks for reaching out. The question is whether your empty cells represent:

1. missing data, in which case you should put NA
2. an actual zero (as in 0 kg), in which case you should put 0

That said, you can leave the cells empty, and once I know the answer to the question, I can do this in the final tidying process with R.

**Comment by raulalexb** [comment]
Thanks @larnsce ! They should represent 0, as in 0 amounts (in numbers) collected, so your second example. In this case I will leave them empty, is that okay? Thanks again for your help!

**Comment by larnsce** [comment]
Okay, great. Yes, leave them empty and I will reformat them to 0s. 

Do you have empty cells for other variables?

**Comment by raulalexb** [comment]
No I do not, just the the cells that had 0 amounts collected on a given day ;)

**Comment by raulalexb** [comment]
Hi @larnsce !
I just uploaded both my data and Chiara's data. I added a litte readme, but this will obviously get updated with better information in the future. 
Important for the data: I formatted my data so that it is all one big chunk of information that can be converted (hopefully easily) into a .csv file. Chiara's data is split into two, the beach data and the riverboom data. Since her riverboom data has no dates, I put it into a seperate section. Should I just add her litterboom data into the main sectionig block, and just put that the date is N/A? 

Thanks again for your time and help ;)

Best,

Raúl

**Comment by larnsce** [comment]
Hi @raulalexb, thank you for writing up the README and adding the data. 

I will start with your data for now, and will then follow up with Chiara's. When there is no date, then you can add NA, but leave it as is now.

Questions:

1. In your data, what does the first untitled column represent? It's a running id from 1 to 14, but what are the groups?
2. When the date column says "06.09." does that represent 6th September 2022?
3. What units are the columns for "Weight of PET" and "Weight of HDPE/PP"? Did you weigh each piece individually or all of them together after separation?
4. Locations: Can you please get the exact coordinates in latitude and longitude for these six locations? You can add them to this file in your browser (see screenshot below): https://github.com/Global-Health-Engineering/durbanplasticwaste22/blob/main/data-raw/litterboom-sample-locations.csv

![Screenshot 2023-02-28 at 09 15 01](https://user-images.githubusercontent.com/18212549/221793749-b1ba1a23-ec17-4e86-8549-e21b3aae1b12.png)

- Click on "Edit this file"
- Then add the longitude and latitude for each location between the commas in the respective column (see below)
- Commit your changes at the bottom of the page

![Screenshot 2023-02-28 at 09 17 44](https://user-images.githubusercontent.com/18212549/221794157-b86a4f2e-8a3f-4a0d-9bd0-89ad597541f1.png)

**Comment by larnsce** [comment]
Another question for the columns "Weight of PET" and "Weight of HDPE/PP":

You have dates where you have 0 for "Weight of PET", but you indicate that you collected items categorised as PET for that date. 

For example, on 14th October (first 10 rows of 336 rows):

|date       |brand                 |plastic | amount| weight_pet|
|:----------|:---------------------|:-------|------:|----------:|
|2022-10-14 |Sunshine D            |PET     |      2|          0|
|2022-10-14 |d'Lite                |HDPE/PP |     10|          0|
|2022-10-14 |NOLA                  |HDPE/PP |      3|          0|
|2022-10-14 |YUM YUM               |HDPE/PP |      2|          0|
|2022-10-14 |Checker's House Brand |HDPE/PP |      1|          0|
|2022-10-14 |Gentle Magic          |PET     |      2|          0|
|2022-10-14 |Woolworths Food       |HDPE/PP |      9|          0|
|2022-10-14 |UnID Medical          |HDPE/PP |     66|          0|
|2022-10-14 |DEO                   |HDPE/PP |     35|          0|
|2022-10-14 |OTHER                 |HDPE/PP |    183|          0|

What happened in these cases? Did you not actually weigh the PET on those days?

**Comment by raulalexb** [comment]
Hi @larnsce! 

Thank you for looking into my data :) 

To your questions:

1) I forgot to title the first column, sorry! It’s supposed to be the collection day. In example, all the data with “1” was collected on the first day of collection, the data with a “4” on the fourth, and so on… 

2) Yes, 06.09 represents September 6th

3) The weights are in kg. The way the weights work is that all the PET and HDPE/PP weight is weighed before and after collection (as a check). Since this only yields us with two data points per collection, I decided to write those two data points for every row on the same collection date. This part was tricky for me, but I hope it is understandable now. 

4) Of course! I will do that right now.

Thanks once more! 

Let me know if this clears up your questions.

Saludos,

Raúl

**Comment by raulalexb** [comment]
@larnsce To your last question concerning the PET and HDPE/PP weights.

Yes there are days with 0 PET weight where we still did collect PET, that is because there were only single bottles on that day, usually less than 10, which didn't even weigh 1kg all together. Since the scale's accuracy was lower than the actual weight of a handful of bottles, it wasn't even worth writing them down. I hope that clarifies it ;)

**Comment by raulalexb** [comment]
@larnsce 

I finished the name changes and uploaded the coordinates for the locations.

**Comment by larnsce** [comment]
> I finished the name changes and uploaded the coordinates for the locations.

Great work on the name changes. I should have specified the coordinates better. Please update them and provide them in decimal format (e.g. 34.576482).

**Comment by larnsce** [comment]
@raulalexb: Is that something you could do? 

> > I finished the name changes and uploaded the coordinates for the locations.
> 
> Great work on the name changes. I should have specified the coordinates better. Please update them and provide them in decimal format (e.g. 34.576482).
