### ISSUE TITLE
Tidy groups in variables

### ISSUE THREAD

**Issue by larnsce** [Global-Health-Engineering/durbanplasticwaste#2]
Hi @raulalexb. I have reviewed the variables and identified several inconsistencies in naming the values for the `brand` and `group` variables.

To fix the `brand` column, can you please run through the XLSX file ([download tidy-brand-names.xlsx](https://github.com/Global-Health-Engineering/durbanplasticwaste22/raw/main/data-raw/tidy-brand.names.xlsx)) and in column "new_name" add a unique name for each brand where you see several names popping up? 

The brand column is ordered alphabetically, so in most cases, the inconsistent names are beneath each other. 

See an example for two brands in this table:

| brand       | count | new_name    |
|-------------|-------|-------------|
| activo vite | 1     | Activo Vite |
| Activo Vite | 1     | Activo Vite |
| avon        | 2     | Avon        |
| Avon        | 1     | Avon        |
| AVON        | 14    | Avon        |

You can edit the XLSX locally on your computer and then upload it again. Please save the file as a new name before uploading it (e.g. tidy-brand-names-rb.xlsx). 

To fix the group column, can you please answer the following questions:

- Is OTHER and OTHER GROUPS the same?
- Is The Coca-Cola Company and Coca Cola Company the same?
- What about UnID Medical, UnID Oils, UnID PET, and UnID Water? Can they all be categorised as UnID?

I realise it's a lot of extra manual work to run through the XLSX, but it will help us share a clean and consistent dataset. Thanks for your efforts.

**Comment by raulalexb** [comment]
Hi @larnsce!

Thank you for looking into this. Of course, I will work on that right after finishing the coordinates. Thanks again for your time and I'm sorry for any troubles this has been causing!

Regarding the group column:
1) This is a bit tricky, but I decided to seperate them. The reason is the following: Other are brands I could not recognize, but that appeared in large numbers. They were either not recognizable because either the name was not legible, or the waste item was not integral. Other groups was meant for all the brands that could be identified but appeared less than two times on average per collection date. I wasn't sure how to differentiate them in the name, but I am glad you reached out regarding this. Does my description make any sense? If not I could call you or meet you regarding this to better explain my reasoning. Thanks :)

2) Yes, that was a naming mistake. They are the same. Theoretically I would have to name all of them Coca-Cola Beverages South Africa (CCBSA).

3) They are all unidentified. However upon collection, I decided to already categorize them, to have a feeling of how large the respective categories were. I did this, as the categorization of most of the items only happened in post data analysis, and not on the field. Therefore I already seperated the unidentified items.

**Comment by raulalexb** [comment]
@larnsce Also, thank you so much for your time and help :)

**Comment by larnsce** [comment]
> This is a bit tricky, but I decided to seperate them. The reason is the following: Other are brands I could not recognize, but that appeared in large numbers. They were either not recognizable because either the name was not legible, or the waste item was not integral. Other groups was meant for all the brands that could be identified but appeared less than two times on average per collection date. I wasn't sure how to differentiate them in the name, but I am glad you reached out regarding this. Does my description make any sense? If not I could call you or meet you regarding this to better explain my reasoning. Thanks :)

Yes, that makes sense. But, I would still suggest to bring them both together into one category, titled "other".

> They are all unidentified. However upon collection, I decided to already categorize them, to have a feeling of how large the respective categories were. I did this, as the categorization of most of the items only happened in post data analysis, and not on the field. Therefore I already seperated the unidentified items.

I would also suggest here to bring them all together as one group "unidentifiable"

**Comment by raulalexb** [comment]
Okay @larnsce, that makes sense, thanks ;)

**Comment by larnsce** [comment]
Brilliant work, thank you for the refactored xlsx file.

I have noticed that the `category` variable has a value called "Bucket". What is that?
