### ISSUE TITLE
Add MSc Semester Project details to README.rmd

### ISSUE THREAD

**Issue by larnsce** [Global-Health-Engineering/durbanplasticwaste#5]
Hi @ChiaraMP. @raulalexb and I have prepared the repo for publishing your data from Durban as an R data package. I still need to transform your data into a tidy data set, but it would be great if you could write up some descriptive information about your semester project.

There are three sections where I need a few sentences. The text is contained in a README.rmd, which then displays the rendered content on the GitHub entry site of the repository and later on a separate website.

- the README.rmd to edit: https://github.com/Global-Health-Engineering/durbanplasticwaste22/blob/cb4b4c647018fe8f6c4d592763ad8659acdc8c22/README.Rmd#L125
- the displayed information: https://github.com/Global-Health-Engineering/durbanplasticwaste22#durbanplasticwaste22

Can you support us in putting together the information? You can either:

- Clone the repo and edit the README.rmd yourself (let me know if you need access to RStudio IDE and R), or
- Share your text here, and I will edit the README.rmd

If you want to clone the repo and push the changes yourself, you will first need to accept my invitation to collaborate on this repo. You should have received an email.

Thanks for your support.

**Comment by ChiaraMP** [comment]
Hey @larnsce 

Sorry for my belated reply. I added a description of my project, but I am not sure if the Pull request went through so I added the information to this comment as well. If I can help you with anything else, please let me know.

### MSc. Semester Project

Examination of non-recycled marine plastic litter in order to identify recycling and beneficiation pathways in Durban, South Africa

###Description

This Semester Thesis Project focuses on determining the distribution of plastic litter on the Durban beachfront in order to identify key targets for policy and financial support through the South African EPR policy to reduce plastic spills into the environment and promote higher recycling rates.

### Research Question

What types and amounts of plastic are found along the beachfront in the mangroves of Durban-North, South Africa?

**Comment by larnsce** [comment]
Hi @ChiaraMP. Great, thank you so much.

I will probably get back to you with more questions once I have tidied the data.

I don't see the pull request. Did you use a RStudio IDE on your personal laptop? It would be great if that information was submitted with a commit and pull request from your side.

We could have a brief call and I can support you getting it through.
